from tictactoe.const import PLAYER_1, PLAYER_2

# START AS A PLAYER 1 (X) OR PLAYER 2 (O)
PLAYER = PLAYER_1
# PLAYER = PLAYER_2

# SIZE OF THE BOARD
BOARD_SIZE = 4

# LENGTH OF THE WINNING SEQUENCE
WIN_SEQUENCE = 3

# DEPTH OF THE MINIMAX ALGORITHM
AI_DIFFICULTY = 4
